#!/bin/sh
# Copyright (c) 2011, Couchbase, Inc.
# All rights reserved.
cd `dirname $0`
exec erl -pa ebin -boot start_sasl -sasl errlog_type error -noshell -run ns_log_browser -report_dir logs/"$1" -run init stop -- "$@"
