#!/bin/sh
# Copyright (c) 2011, Couchbase, Inc.
# All rights reserved.

COUCHBASE_BIN=`dirname "$0"`
COUCHBASE_TOP=`dirname "$COUCHBASE_BIN"`
export COUCHBASE_TOP

PATH="$COUCHBASE_BIN":$PATH
export PATH

ERL_LIBS="$COUCHBASE_TOP/lib/couchdb/erlang/lib:$COUCHBASE_TOP/lib/ns_server/erlang/lib"
export ERL_LIBS

if [ x"$1" != "x" ]
then
    extra_args="-log $1"
fi

exec erl -pa ebin -noshell -run ns_log_browser \
         -report_dir "$COUCHBASE_TOP/var/lib/couchbase/logs" ${extra_args} \
         -run init stop -- "$@"
