#!/bin/sh
#
# @author Couchbase <info@couchbase.com>
# @copyright 2016 Couchbase, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Extract cpu utilization stats from stats archive.
#
# Example usage:
#
#   ./cpu --period minute stats_archives.json | jq 'sort_by(.total_cpu)'
#

PERIOD=hour
ARGS=$(getopt -o p: -l period: -n "$0" -- "$@")

if [ $? != 0 ]; then
    exit 1
fi

eval set -- "$ARGS"

while true; do
    case "$1" in
        -p|--period) PERIOD=$2; shift 2;;
        --) shift; break;;
    esac
done

exec jq --arg period "$PERIOD" '
.["@system-processes"][$period].samples
| map((.sample | with_entries(select(.key | test("cpu_utilization")))) as $cpu
      | ($cpu | values | add) as $total
      | {ts: .ts, total_cpu: $total, cpu: $cpu})
' "$@"
