#!/usr/bin/env ruby
#
# @author Couchbase <info@couchbase.com>
# @copyright 2012 Couchbase, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require 'rubygems'
require 'sinatra'
require 'json'
# gem install rack-contrib
require 'rack/contrib/jsonp'
require 'pp'

use Rack::JSONP

get '/home' do
  content_type :json
  puts "got params:"
  pp params
  reply = {
    'newVersion' => '1.8.3',
    'links' => {
      :download => 'http://google.com/?q=couchbase+server+download',
      :release => 'http://google.com/?q=couchbase+server+release+notes'
    },
    :info => 'some crap?'
  }
  # sleep a bit to simulate internet delay
  sleep 3.8
  reply.to_json
end

post '/home' do
  statsBody = params['stats']
  data = JSON.parse(statsBody)
  puts "got phone home package"
  pp data

  content_type :html
  '""'
end
