#!/bin/sh
#
# @author Couchbase <info@couchbase.com>
# @copyright 2016 Couchbase, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Filter only events relevant to last rebalance.
#

exec jq '
(length as $size |
 to_entries |
 map({key: .key, type: .value.type} |
     select(.type == "rebalanceStart" or
            .type == "rebalanceEnd")) |
 (length - 1) as $last |
 if .[$last].type == "rebalanceEnd" then
   [.[$last-1].key, .[$last].key+1]
 else
   [.[$last].key, $size]
 end) as [$a,$b] | .[$a:$b]
' "$@"
