#!/bin/sh
#
# @author Couchbase <info@couchbase.com>
# @copyright 2016 Couchbase, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Decode .ts in a stream of objects to human readable datetime.
#
# Example usage:
#   ./cpu --period minute stats_archives.json | ../human-time --offset -700
#

OFFSET=$(date +%z)
ARGS=$(getopt -o o: -l offset: -n "$0" -- "$@")

if [ $? != 0 ]; then
    exit 1
fi

eval set -- "$ARGS"

while true; do
    case "$1" in
        -o|--offset) OFFSET=$2; shift 2;;
        --) shift; break;;
    esac
done

exec jq --argjson offset "$OFFSET" '
def abs:
  if (. < 0) then -. else . end;

def formatTime:
  (($offset / 100) | floor) as $offsetHours
  | (($offset % 100) | abs) as $offsetMinutes
  | (($offsetHours * 60 + $offsetMinutes) * 60) as $offsetSeconds
  | (. % 1000) as $ms
  | (. / 1000) + $offsetSeconds
  | strftime("%Y-%m-%dT%H:%M:%S") + ".\($ms)";

map((.ts | formatTime) as $date
    | . + {date: $date})
' "$@"
